Updated names in intro example
RedisGears/RedisGears pull request #539
Opened 2021-04-23 18:03 UTC by justincastilla

Mr. Poopybutthole and Fart may offend some of our more sensitive readers.  I've replaced them with two other 'safe' names.

2021-04-23 18:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisGears/RedisGears?pullRequest=539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisGears/RedisGears?pullRequest=539) before we can accept your contribution.<br/><hr/>**Justin Castilla** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisGears/RedisGears?pullRequest=539) it.</sub>

2021-04-24 10:57 UTC, itamarhaber commented on docs/intro.md
> +Consider, however, what will happen once we start adding Revolio Clockberg Jr. (a.k.a Gearhead), Donna Gueterman, Birdperson, Reverse Giraffe and the rest of the multiverse to the database. The numbe
```suggestion
Consider, however, what will happen once we start adding Revolio Clockberg Jr. (a.k.a Gearhead),  Birdperson, and the rest of the multiverse to the database. The number of input records and the number of families will increase accordingly, causing more and more records to be moved across the network and resulting in higher latencies.
```

2021-04-24 11:01 UTC, itamarhaber requested changes
Kudos @justincastilla for surviving that wall of text. If that's the only issue found with it, I can die a happy person.

2023-11-17 16:53 UTC, justincastilla commented
Original intent has been satisfied.

2023-11-17 16:53 UTC, closed without merging